/**
 * components/ui/illustrations.tsx
 *
 * SERVER COMPONENTS. Inline SVG spot illustrations for empty states.
 *
 * ==========================================================================
 * NO TAILWIND COLOUR CLASSES IN HERE. DELIBERATELY.
 * ==========================================================================
 * The first version of this file painted itself with utilities —
 * `fill-brand-50`, `stroke-brand-300`, `fill-slate-200`. That worked, and then
 * failed in the worst possible way: a stylesheet built before this file existed
 * had none of those classes generated, so every fill and stroke resolved to
 * nothing and the drawings rendered as a large, silent, blank box. Utilities are
 * generated by scanning source files, so a decorative graphic that depends on
 * them has a hard dependency on the build being current.
 *
 * So the colour comes from `currentColor` and OPACITY, expressed as plain SVG
 * attributes. That has four consequences worth the trade:
 *
 *   1. It cannot silently disappear. With zero CSS the drawing still paints,
 *      because `stroke="currentColor"` is an attribute, not a class.
 *   2. One hue, three tonal steps. Tinting is `opacity`, so the whole set is
 *      automatically coherent with whatever colour the container sets — change
 *      the parent's text colour and every drawing follows.
 *   3. A palette change needs no edit here at all.
 *   4. It stays legible in forced-colors / high-contrast mode, where background
 *      fills are overridden but currentColor strokes survive.
 *
 * ==========================================================================
 * THEY ARE DECORATION, AND MARKED AS SUCH
 * ==========================================================================
 * Every one is aria-hidden. The EmptyState beside them carries a real heading
 * and a sentence saying what is going on and what to do next — a screen-reader
 * user gets the whole meaning from the text, and "illustration of an empty
 * calendar" adds nothing but noise.
 *
 * Construction rules, so the set reads as one family:
 *   - a single 96×96 viewBox
 *   - 1.5 stroke width, round caps and joins
 *   - three tonal steps only: WASH (0.07), FILL (0.16), ACCENT (0.4)
 *   - one accent detail per drawing, never more
 */

type IllustrationProps = {
  className?: string;
};

/** The three tonal steps. Named so a drawing cannot invent a fourth. */
const WASH = 0.07;
const FILL = 0.16;
const ACCENT = 0.4;

/**
 * Shared frame. `stroke="currentColor"` sits here as an ATTRIBUTE so it is
 * inherited by every child and survives with no stylesheet at all.
 */
function Frame({
  className = '',
  children,
}: IllustrationProps & { children: React.ReactNode }) {
  return (
    <svg
      viewBox="0 0 96 96"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      aria-hidden="true"
      focusable="false"
      className={className}
    >
      {children}
    </svg>
  );
}

/** The soft disc every drawing sits on. */
function Wash() {
  return (
    <circle cx="48" cy="48" r="36" fill="currentColor" opacity={WASH} stroke="none" />
  );
}

/** Nothing booked / no classes scheduled. */
export function EmptyCalendarArt({ className }: IllustrationProps) {
  return (
    <Frame className={className}>
      <Wash />
      <rect x="24" y="26" width="48" height="44" rx="6" />
      <path d="M24 38h48" />
      <path d="M36 26v-6M60 26v-6" />
      {/* Empty day cells — the subject of the drawing. */}
      <rect x="32" y="46" width="8" height="7" rx="2" fill="currentColor" opacity={FILL} stroke="none" />
      <rect x="44" y="46" width="8" height="7" rx="2" fill="currentColor" opacity={FILL} stroke="none" />
      <rect x="56" y="46" width="8" height="7" rx="2" fill="currentColor" opacity={FILL} stroke="none" />
      <rect x="32" y="58" width="8" height="7" rx="2" fill="currentColor" opacity={FILL} stroke="none" />
      {/* The one accent: a single highlighted slot, hinting "this could be
          filled". */}
      <rect x="44" y="58" width="20" height="7" rx="3.5" fill="currentColor" opacity={ACCENT} stroke="none" />
    </Frame>
  );
}

/** No alerts. */
export function EmptyBellArt({ className }: IllustrationProps) {
  return (
    <Frame className={className}>
      <Wash />
      <path d="M48 24a13 13 0 0 0-13 13v10l-4 8h34l-4-8V37a13 13 0 0 0-13-13Z" />
      <path d="M42 63a6 6 0 0 0 12 0" />
      {/* Quiet lines rather than a notification dot — the absence IS the
          message, so nothing here should resemble an unread badge. */}
      <path d="M26 40h-6M28 50h-8" opacity={ACCENT} />
      <path d="M70 40h6M68 50h8" opacity={ACCENT} />
    </Frame>
  );
}

/** No students / nobody on the roster. */
export function EmptyPeopleArt({ className }: IllustrationProps) {
  return (
    <Frame className={className}>
      <Wash />
      {/* Two solid figures and one dashed outline: the dashed one is the
          invitation — a space shaped like a person who is not here yet. */}
      <circle cx="36" cy="41" r="7" />
      <path d="M25 64c0-6.1 4.9-11 11-11s11 4.9 11 11" />
      <circle cx="58" cy="44" r="6" />
      <path d="M49 64c0-5 4-9 9-9s9 4 9 9" />
      <circle cx="72" cy="38" r="8" strokeDasharray="3 3" opacity={ACCENT} />
      <path d="M72 34v8M68 38h8" opacity={ACCENT} />
    </Frame>
  );
}

/** No credits. */
export function EmptyTicketArt({ className }: IllustrationProps) {
  return (
    <Frame className={className}>
      <Wash />
      <path d="M26 40a4 4 0 0 1 4-4h36a4 4 0 0 1 4 4v4a5 5 0 0 0 0 10v4a4 4 0 0 1-4 4H30a4 4 0 0 1-4-4v-4a5 5 0 0 0 0-10v-4Z" />
      {/* The perforation, which is what makes it read as a ticket at 80px. */}
      <path d="M48 40v3M48 47v3M48 54v3" opacity={ACCENT} />
      <path d="M33 46h8M33 52h5" opacity={ACCENT} />
    </Frame>
  );
}

/** No history / nothing has happened yet. */
export function EmptyHistoryArt({ className }: IllustrationProps) {
  return (
    <Frame className={className}>
      <Wash />
      <circle cx="48" cy="48" r="20" />
      {/* Hands at 10:10 — the conventional clock reading, and the only pose
          that does not look like a specific meaningful time. */}
      <path d="M48 38v10l7 5" />
      <path d="M48 24v3M48 69v3M24 48h3M69 48h3" opacity={ACCENT} />
      <path d="M64 32a20 20 0 0 1 4 8" opacity={ACCENT} />
    </Frame>
  );
}

/** Nothing to report / no data in the window. */
export function EmptyChartArt({ className }: IllustrationProps) {
  return (
    <Frame className={className}>
      <Wash />
      <path d="M28 66h40" />
      <path d="M28 30v36" />
      {/* Flat, low bars: "no data" rather than "bad data" — nothing here should
          look like a downward trend, which would read as a real measurement. */}
      <rect x="36" y="58" width="8" height="8" rx="2" fill="currentColor" opacity={FILL} stroke="none" />
      <rect x="48" y="54" width="8" height="12" rx="2" fill="currentColor" opacity={FILL} stroke="none" />
      <rect x="60" y="58" width="8" height="8" rx="2" fill="currentColor" opacity={ACCENT} stroke="none" />
    </Frame>
  );
}
